### ISSUE TITLE
args example Error in alias analysis

### ISSUE THREAD

**Issue by Anton-4** [roc-lang/basic-cli#90]
```
+ ./roc_nightly/roc build --linker=legacy ./examples/args.roc
🔨 Rebuilding platform...
thread 'main' panicked at 'Error in alias analysis: error in module ModName("UserApp"), function definition FuncName("\x1b\x00\x00\x00\x12\x00\x00\x00\xbe\xd12$b\x077\x15"), definition of value binding ValueId(59): could not find func in module ModName("UserApp") with name FuncName("\x8c\x00\x00\x00\x12\x00\x00\x00\x1d\xca$\xf15\xe8\xd8\x98")', crates/compiler/gen_llvm/src/llvm/build.rs:5094:19
```
This is a recent regression in roc, I should be able to bisect this soon.

**Comment by Anton-4** [comment]
This was caused by https://github.com/roc-lang/roc/pull/5576

**Comment by Anton-4** [comment]
```
RUST_BACKTRACE=1 ./target/release/roc build --linker=legacy /home/username/gitrepos/basic-cli/examples/args.roc
🔨 Rebuilding platform...
thread 'main' panicked at 'Error in alias analysis: error in module ModName("UserApp"), function definition FuncName("\x1b\x00\x00\x00\x12\x00\x00\x00\xbe\xd12$b\x077\x15"), definition of value binding ValueId(59): could not find func in module ModName("UserApp") with name FuncName("\x8c\x00\x00\x00\x12\x00\x00\x00\x1d\xca$\xf15\xe8\xd8\x98")', crates/compiler/gen_llvm/src/llvm/build.rs:5094:19
stack backtrace:
   0: rust_begin_unwind
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:64:14
   2: roc_gen_llvm::llvm::build::build_procedures_help
   3: roc_gen_llvm::llvm::build::build_procedures
   4: roc_build::program::gen_from_mono_module
   5: roc_build::program::build_loaded_file
   6: roc_build::program::build_file
   7: roc_cli::build
   8: roc::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by Anton-4** [comment]
Further discussion will  happen in https://github.com/roc-lang/roc/issues/5701

**Comment by lukewilliamboswell** [comment]
Agent review note: I’m an OpenAI Codex Agent tasked to review the open `basic-cli` issues in support of the major upgrade to the new Zig-based Roc compiler.

**Recommendation: Close as obsolete.** This was a legacy LLVM alias-analysis/compiler regression associated with the removed legacy linker. The linked upstream compiler issue is closed, and the current command-line arguments example passes check/test in the Zig-compiler matrix.
